### ISSUE TITLE
The filter does not work

### ISSUE THREAD

**Issue by WebNetCrea** [netzmacht/contao-leaflet-metamodels#4]
Hi,
Contao 4.4.45
MM 2.1.2
MetaModels Integration 3.0.0 RC1

The filter does not work with maps but it works with the MM list under the Map.
([https://www.therapie-interpersonnelle.fr/annuaire.html])
It's a bug, or maybe I forgot something ?
Thank's
![FireShot Capture 018 - Map Layers › Edit layer ID 1 - Contao Open Source CMS_ - therapie-interpersonnelle fr](https://user-images.githubusercontent.com/3774879/71108202-e6eec080-21c2-11ea-950b-b6649f89fa1b.png)

**Comment by dmolineus** [comment]
Your filter is applied as part of the url. This library doesn't support it at the moment. If the filter is applied as get parameter, everything works fine, see https://www.therapie-interpersonnelle.fr/annuaire.html?pays=france

**Comment by dmolineus** [comment]
e8a02aae8120fa20f49fdc750825345cc86e4728 should fix it, at the moment only part of the develop branch

**Comment by dmolineus** [comment]
Fixed in release 3.0.0
